# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5f208e9b519cad1884997f87613609e2365efac41b036466e470696672b2b0ce959ee8bcd5795d1f30b6edb8bafcdabb916019314cc47cbd37d7fc898e57fdb

test:
  secret_key_base: bd3cbcea7d01a5e08287b84b3daf81d5af75a20a9f1831f0c00bc61a50300626164d5bc6fef6b863e130aec5173143930c5baf96dd005763db2216cb6eea1d3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
